name: url_shortener

services:
  # app:
  #   build: .
  #   env_file:
  #     - .envrc
  #   ports:
  #     - 4000:4000
  #   restart: unless-stopped
  #   depends_on:
  #     - pg
  pg:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: postgres
    env_file:
      - .envrc
    volumes:
      - pg:/data/db
    ports:
      - 5432:5432

volumes:
  pg:
